// ============================================
// HUMAN DESIGN REFERENCE DATA
// ============================================

export const HD_TYPES = {
  Manifestor: {
    population: '9%',
    strategy: 'To Inform',
    not_self_theme: 'Anger',
    signature: 'Peace',
    aura: 'Closed and Repelling',
    description: 'Manifestors are the initiators of the HD world. They have the power to start things and make things happen. Their strategy is to inform those they impact before taking action.',
    affirmations: [
      'I inform before I act',
      'My initiation is a gift to the world',
      'Peace is my natural state when I honor my design',
      'I do not need permission to be who I am',
    ],
    journal_prompts: [
      'Did I inform others before taking action today? How did it feel?',
      'Where did I feel anger today — was I not informing, or being blocked?',
      'What did I initiate today that felt aligned?',
      'How did I experience peace in my body today?',
    ],
  },
  Generator: {
    population: '37%',
    strategy: 'To Respond',
    not_self_theme: 'Frustration',
    signature: 'Satisfaction',
    aura: 'Open and Enveloping',
    description: 'Generators are the life force of the planet. They have a defined Sacral center and are here to find work they love. They must wait to respond — their gut knows.',
    affirmations: [
      'I trust my sacral response',
      'I wait to respond and life brings what is right for me',
      'My satisfaction comes from doing what lights me up',
      'Frustration is a signal to pause, not push',
    ],
    journal_prompts: [
      'What did my sacral respond to today — "uh-huh" or "un-un"?',
      'Did I push or force anything today? How did it feel?',
      'What brought me genuine satisfaction and lit me up?',
      'Where did I feel frustration — was I initiating instead of responding?',
    ],
  },
  'Manifesting Generator': {
    population: '33%',
    strategy: 'To Respond, then Inform',
    not_self_theme: 'Frustration & Anger',
    signature: 'Satisfaction & Peace',
    aura: 'Open and Enveloping',
    description: 'Manifesting Generators are a hybrid — they have Sacral energy AND a motor connected to the throat. They are multi-passionate, fast-moving, and here to find the most efficient path.',
    affirmations: [
      'I respond first, then inform',
      'My zigzag path is perfect for me',
      'I can do many things at once — that is my design',
      'Skipping steps is allowed when my gut says go',
    ],
    journal_prompts: [
      'What did I respond to today before acting?',
      'Did I skip steps — was that aligned or avoidant?',
      'What multiple projects am I juggling and how do they feel?',
      'Did I inform those impacted by my actions today?',
    ],
  },
  Projector: {
    population: '21%',
    strategy: 'Wait for the Invitation',
    not_self_theme: 'Bitterness',
    signature: 'Success',
    aura: 'Focused and Absorbing',
    description: 'Projectors are the guides and managers of the HD world. They see deeply into others and systems. They must wait for recognition and invitation before sharing their wisdom.',
    affirmations: [
      'I wait for the genuine invitation',
      'My wisdom is valuable and worth waiting for',
      'Rest is productive for my design',
      'Success comes when I am recognized and invited',
    ],
    journal_prompts: [
      'Did I wait for an invitation today, or did I offer unsolicited advice?',
      'Where did I feel bitterness — was I unseen or not invited?',
      'How did I honor my need for rest today?',
      'What recognition did I receive today, and how did it feel?',
    ],
  },
  Reflector: {
    population: '1%',
    strategy: 'Wait a Lunar Cycle',
    not_self_theme: 'Disappointment',
    signature: 'Surprise',
    aura: 'Resistant and Sampling',
    description: 'Reflectors are the rare mirrors of humanity. With all centers undefined, they reflect the health of their community. They need a full lunar cycle (28 days) before making major decisions.',
    affirmations: [
      'I am a mirror reflecting the world\'s health',
      'I take my time — 28 days for big decisions',
      'My inconsistency is my consistency',
      'I am here to experience life\'s surprises',
    ],
    journal_prompts: [
      'How did the people around me feel today — what did you reflect back?',
      'What environment felt good vs. draining today?',
      'Am I giving myself a full lunar cycle for big decisions?',
      'What delightful surprises showed up today?',
    ],
  },
}

export const HD_AUTHORITIES = {
  Sacral: {
    center: 'Sacral',
    description: 'Your gut knows. The sacral speaks through sounds — "uh-huh" (yes) or "un-un" (no). It\'s pre-verbal and immediate. Trust the body.',
    how_to_use: 'Ask yes/no questions out loud. Listen for the gut sound or physical sensation before your mind has a chance to analyze.',
    journal_prompt: 'What did your sacral say yes or no to today? Did you listen?',
  },
  'Emotional/Solar Plexus': {
    center: 'Solar Plexus',
    description: 'Your truth emerges in waves over time. There is no truth in the now — you must ride your emotional wave before deciding.',
    how_to_use: 'Sleep on decisions. Notice how you feel across different emotional states (high, low, neutral). Clarity comes with time.',
    journal_prompt: 'What decision are you sitting with? How has your feeling about it shifted over days?',
  },
  Splenic: {
    center: 'Spleen',
    description: 'Spontaneous, in-the-moment knowing. The spleen speaks once and softly. It\'s about survival, intuition, and instinct.',
    how_to_use: 'Trust the first quiet knowing. Don\'t second-guess it. The splenic voice doesn\'t repeat itself.',
    journal_prompt: 'What subtle knowing or instinct arose today? Did you trust it?',
  },
  'Ego/Heart': {
    center: 'Heart/Ego',
    description: 'You make decisions based on what you want and what your willpower supports. You need to ask: "Do I want this? Will I commit to this?"',
    how_to_use: 'Be honest about what you truly desire and what you\'re willing to stand behind.',
    journal_prompt: 'What did your heart/ego truly want today? Did you honor it?',
  },
  'G Center/Self': {
    center: 'G Center',
    description: 'Your direction and identity are your authority. You make decisions based on love and direction — who you are and where you\'re going.',
    how_to_use: 'Ask: "Does this feel like me? Does this align with my direction in life?"',
    journal_prompt: 'Did your choices today feel authentically YOU and aligned with your path?',
  },
  'Mental/Environment': {
    center: 'None (Mental)',
    description: 'You need to talk things through with trusted others and pay attention to your environment to find clarity.',
    how_to_use: 'Talk it out with wise, non-invested sounding boards. Notice how your body feels in different environments.',
    journal_prompt: 'Who did you process your thinking with today? What environments felt supportive?',
  },
  Lunar: {
    center: 'None (Lunar)',
    description: 'You are a Reflector. Your authority is the Moon cycle — 28 days of sampling perspectives before deciding.',
    how_to_use: 'Talk to many different people. Track your feelings across the full lunar cycle. Don\'t rush decisions.',
    journal_prompt: 'Where are you in your lunar cycle? How has your feeling about a decision shifted this month?',
  },
}

export const HD_CENTERS = [
  {
    name: 'Head',
    defined_gift: 'Consistent mental pressure and inspiration',
    open_gift: 'Broad range of mental inspiration from others',
    open_conditioning: 'Pressure to figure everything out; mental anxiety',
    not_self_question: 'Am I trying to answer questions that aren\'t mine?',
    color: '#8B5CF6',
  },
  {
    name: 'Ajna',
    defined_gift: 'Consistent way of conceptualizing and processing',
    open_gift: 'Mental flexibility and seeing many perspectives',
    open_conditioning: 'Needing to appear certain; mental anxiety about knowing',
    not_self_question: 'Am I trying to be certain when I\'m not?',
    color: '#6D28D9',
  },
  {
    name: 'Throat',
    defined_gift: 'Consistent voice and way of expressing/manifesting',
    open_gift: 'Versatile communicator, many voices',
    open_conditioning: 'Talking to be heard; attention-seeking',
    not_self_question: 'Am I talking just to get attention?',
    color: '#2563EB',
  },
  {
    name: 'G Center',
    defined_gift: 'Fixed sense of identity, direction, and love',
    open_gift: 'Open to many directions and identities; seeks love',
    open_conditioning: 'Asking "Who am I? Where am I going?" with anxiety',
    not_self_question: 'Am I looking for love and direction in the wrong places?',
    color: '#D97706',
  },
  {
    name: 'Heart/Ego',
    defined_gift: 'Consistent willpower, self-worth, and ability to commit',
    open_gift: 'Not here to prove themselves; wisdom about willpower',
    open_conditioning: 'Proving self-worth; overcommitting to prove value',
    not_self_question: 'Am I trying to prove my worth?',
    color: '#DC2626',
  },
  {
    name: 'Sacral',
    defined_gift: 'Life force, sustainable work energy, gut knowing',
    open_gift: 'Amplifies others\' sacral energy; wisdom about life force',
    open_conditioning: 'Not knowing when to stop; over-working',
    not_self_question: 'Do I know when enough is enough?',
    color: '#B45309',
  },
  {
    name: 'Solar Plexus',
    defined_gift: 'Consistent emotional wave; truth emerges over time',
    open_gift: 'Emotional sensitivity and empathy; feels others deeply',
    open_conditioning: 'Avoiding truth and conflict to keep peace',
    not_self_question: 'Am I avoiding truth to keep the peace?',
    color: '#D97706',
  },
  {
    name: 'Spleen',
    defined_gift: 'Consistent intuition, immune system, survival instincts',
    open_gift: 'Highly attuned to others\' health and intuition',
    open_conditioning: 'Holding on to what isn\'t healthy out of fear',
    not_self_question: 'Am I holding on to something because I\'m afraid?',
    color: '#059669',
  },
  {
    name: 'Root',
    defined_gift: 'Consistent adrenaline and pressure to fuel action',
    open_gift: 'Wisdom about pressure and stress; knows when to act',
    open_conditioning: 'Always in a rush to get things done to relieve pressure',
    not_self_question: 'Am I always in a hurry to relieve pressure?',
    color: '#7C3AED',
  },
]

export const GATES_64: Record<string, { name: string; keyword: string; description: string; shadow: string; gift: string; siddhi: string }> = {
  '1': { name: 'Gate of Self-Expression', keyword: 'Creativity', description: 'The energy of creative self-expression and the power of originality.', shadow: 'Entropy', gift: 'Freshness', siddhi: 'Beauty' },
  '2': { name: 'Gate of the Direction of Self', keyword: 'Higher Knowing', description: 'Knowing the direction of the self; receptivity to guidance.', shadow: 'Dislocation', gift: 'Orientation', siddhi: 'Unity' },
  '3': { name: 'Gate of Ordering', keyword: 'Innovation', description: 'Mutation and chaos leading to new order; difficulty in beginning.', shadow: 'Chaos', gift: 'Innovation', siddhi: 'Innocence' },
  '4': { name: 'Gate of Formulization', keyword: 'Solutions', description: 'Mental formulas and answers waiting to be applied.', shadow: 'Intolerance', gift: 'Understanding', siddhi: 'Forgiveness' },
  '5': { name: 'Gate of Fixed Rhythms', keyword: 'Patterns', description: 'Universal flow and the power of habit and rhythm.', shadow: 'Victimization', gift: 'Patience', siddhi: 'Timelessness' },
  '6': { name: 'Gate of Friction', keyword: 'Conflict', description: 'Emotional friction as the gateway to intimacy.', shadow: 'Conflict', gift: 'Diplomacy', siddhi: 'Peace' },
  '7': { name: 'Gate of the Role of the Self', keyword: 'Leadership', description: 'The alpha — leadership through example and democratic guidance.', shadow: 'Division', gift: 'Guidance', siddhi: 'Virtue' },
  '8': { name: 'Gate of Contribution', keyword: 'Uniqueness', description: 'Contribution through individual expression and making a difference.', shadow: 'Mediocrity', gift: 'Style', siddhi: 'Exquisiteness' },
  '9': { name: 'Gate of Focus', keyword: 'Determination', description: 'Focused energy for details; the power of concentration.', shadow: 'Inertia', gift: 'Determination', siddhi: 'Invincibility' },
  '10': { name: 'Gate of Love of Self', keyword: 'Self-Love', description: 'Behavior and love of self as the foundation of authentic living.', shadow: 'Self-Obsession', gift: 'Naturalness', siddhi: 'Being' },
  '11': { name: 'Gate of Ideas', keyword: 'Ideas', description: 'Harmony and abundance of mental ideas seeking expression.', shadow: 'Obscurity', gift: 'Idealism', siddhi: 'Light' },
  '12': { name: 'Gate of Caution', keyword: 'Caution', description: 'The power of standstill — waiting for the right moment to speak.', shadow: 'Vanity', gift: 'Discrimination', siddhi: 'Purity' },
  '13': { name: 'Gate of the Listener', keyword: 'Narrative', description: 'Fellowship and listening; holding the secrets of humanity.', shadow: 'Discord', gift: 'Empathy', siddhi: 'Cosmic Memory' },
  '14': { name: 'Gate of Power Skills', keyword: 'Power', description: 'Great possession of power and resources for the greater good.', shadow: 'Compromise', gift: 'Competence', siddhi: 'Bounteousness' },
  '15': { name: 'Gate of Extremes', keyword: 'Humanity', description: 'Modesty and love of humanity expressed through rhythms.', shadow: 'Dullness', gift: 'Magnetism', siddhi: 'Florescence' },
  '16': { name: 'Gate of Skills', keyword: 'Enthusiasm', description: 'Enthusiasm and the love of experimentation and mastery.', shadow: 'Indifference', gift: 'Versatility', siddhi: 'Mastery' },
  '17': { name: 'Gate of Opinions', keyword: 'Opinions', description: 'Following and organizing logical opinions.', shadow: 'Opinion', gift: 'Anticipation', siddhi: 'Omniscience' },
  '18': { name: 'Gate of Correction', keyword: 'Judgment', description: 'Correcting imperfection in patterns for the greater good.', shadow: 'Judgment', gift: 'Integrity', siddhi: 'Perfection' },
  '19': { name: 'Gate of Wanting', keyword: 'Wanting', description: 'Sensitivity to needs; wanting connection and sustenance.', shadow: 'Co-dependence', gift: 'Sensitivity', siddhi: 'Sacrifice' },
  '20': { name: 'Gate of the Now', keyword: 'Presence', description: 'Metamorphosis; contemplation and self-awareness in the now.', shadow: 'Superficiality', gift: 'Self-Assurance', siddhi: 'Presence' },
  '21': { name: 'Gate of the Hunter', keyword: 'Control', description: 'Biting through obstacles; the will to control resources.', shadow: 'Control', gift: 'Authority', siddhi: 'Valour' },
  '22': { name: 'Gate of Openness', keyword: 'Grace', description: 'Grace and emotional openness to new experiences.', shadow: 'Dishonour', gift: 'Graciousness', siddhi: 'Grace' },
  '23': { name: 'Gate of Assimilation', keyword: 'Individuality', description: 'Splitting apart to allow new understanding to enter.', shadow: 'Complexity', gift: 'Simplicity', siddhi: 'Quintessence' },
  '24': { name: 'Gate of Rationalization', keyword: 'Return', description: 'The return and rationalization turning confusion into knowing.', shadow: 'Addiction', gift: 'Invention', siddhi: 'Silence' },
  '25': { name: 'Gate of the Spirit of the Self', keyword: 'Innocence', description: 'Universal love and the innocence of the spirit.', shadow: 'Selfishness', gift: 'Acceptance', siddhi: 'Universal Love' },
  '26': { name: 'Gate of the Egoist', keyword: 'Conditioning', description: 'The power of memory and the ego\'s ability to condition others.', shadow: 'Pride', gift: 'Conditioning', siddhi: 'Invisibility' },
  '27': { name: 'Gate of Caring', keyword: 'Caring', description: 'Nourishment and caring for others and the community.', shadow: 'Self-Centeredness', gift: 'Altruism', siddhi: 'Selflessness' },
  '28': { name: 'Gate of the Game Player', keyword: 'Risk', description: 'Struggle and the game of life; finding what makes life worth living.', shadow: 'Purposelessness', gift: 'Totality', siddhi: 'Immortality' },
  '29': { name: 'Gate of Perseverance', keyword: 'Saying Yes', description: 'Perseverance in commitments; the power of saying yes.', shadow: 'Half-heartedness', gift: 'Commitment', siddhi: 'Devotion' },
  '30': { name: 'Gate of Feelings', keyword: 'Feelings', description: 'Emotional depth and the clinging fire of desire.', shadow: 'Desire', gift: 'Lightness', siddhi: 'Rapture' },
  '31': { name: 'Gate of Influence', keyword: 'Influence', description: 'Democratic leadership and natural influence.', shadow: 'Arrogance', gift: 'Leadership', siddhi: 'Humility' },
  '32': { name: 'Gate of Continuity', keyword: 'Endurance', description: 'Duration and recognizing what has value and endures.', shadow: 'Failure', gift: 'Preservation', siddhi: 'Veneration' },
  '33': { name: 'Gate of Privacy', keyword: 'Retreat', description: 'Retreating and the power of witnessing and storytelling.', shadow: 'Forgetting', gift: 'Mindfulness', siddhi: 'Revelation' },
  '34': { name: 'Gate of Power', keyword: 'Power', description: 'The great power of the life force used for the self.', shadow: 'Force', gift: 'Strength', siddhi: 'Majesty' },
  '35': { name: 'Gate of Change', keyword: 'Change', description: 'Progress through change and new emotional experiences.', shadow: 'Hunger', gift: 'Adventure', siddhi: 'Boundlessness' },
  '36': { name: 'Gate of Crisis', keyword: 'Exploration', description: 'The dark side of feelings; transition through crises.', shadow: 'Turbulence', gift: 'Humanity', siddhi: 'Compassion' },
  '37': { name: 'Gate of Friendship', keyword: 'Friendship', description: 'Friendship and the family unit as the foundation of society.', shadow: 'Weakness', gift: 'Equality', siddhi: 'Tenderness' },
  '38': { name: 'Gate of the Fighter', keyword: 'Opposition', description: 'Fighting against opposition to find what is truly worth fighting for.', shadow: 'Stubbornness', gift: 'Perseverance', siddhi: 'Honor' },
  '39': { name: 'Gate of Provocation', keyword: 'Provocation', description: 'Obstruction that provokes the spirit to emerge.', shadow: 'Provocation', gift: 'Dynamism', siddhi: 'Liberation' },
  '40': { name: 'Gate of Aloneness', keyword: 'Alone', description: 'Deliverance and needing time alone after working hard.', shadow: 'Exhaustion', gift: 'Resolve', siddhi: 'Divine Will' },
  '41': { name: 'Gate of Contraction', keyword: 'Fantasy', description: 'Contraction of fantasy and the beginning of new experiences.', shadow: 'Fantasy', gift: 'Anticipation', siddhi: 'Emanation' },
  '42': { name: 'Gate of Growth', keyword: 'Completion', description: 'Growth through completing what has been started.', shadow: 'Incompletion', gift: 'Detachment', siddhi: 'Celebration' },
  '43': { name: 'Gate of Insight', keyword: 'Insight', description: 'Breakthrough insights that come fully formed from within.', shadow: 'Deafness', gift: 'Insight', siddhi: 'Epiphany' },
  '44': { name: 'Gate of Alertness', keyword: 'Patterns', description: 'Alertness to patterns from the past to guide the future.', shadow: 'Interference', gift: 'Teamwork', siddhi: 'Synergy' },
  '45': { name: 'Gate of the Gatherer', keyword: 'Gathering', description: 'Gathering and distributing resources for the community.', shadow: 'Dominance', gift: 'Naturalness', siddhi: 'Communion' },
  '46': { name: 'Gate of the Determination of the Self', keyword: 'Good Fortune', description: 'Love of the body and good fortune through perseverance.', shadow: 'Seriousness', gift: 'Delight', siddhi: 'Ecstasy' },
  '47': { name: 'Gate of Realization', keyword: 'Realization', description: 'Oppression and the realization that meaning comes from within.', shadow: 'Oppression', gift: 'Mindfulness', siddhi: 'Transfiguration' },
  '48': { name: 'Gate of Depth', keyword: 'Depth', description: 'Depth of knowledge; the fear of inadequacy.', shadow: 'Inadequacy', gift: 'Resourcefulness', siddhi: 'Wisdom' },
  '49': { name: 'Gate of Principles', keyword: 'Revolution', description: 'Revolution and principles that trigger transformation.', shadow: 'Reaction', gift: 'Revolution', siddhi: 'Rebirth' },
  '50': { name: 'Gate of Values', keyword: 'Values', description: 'Values, laws, and the responsibility of care.', shadow: 'Corruption', gift: 'Responsibility', siddhi: 'Harmony' },
  '51': { name: 'Gate of Shock', keyword: 'Shock', description: 'The shock of awakening; standing alone in the face of challenge.', shadow: 'Trauma', gift: 'Initiative', siddhi: 'Awakening' },
  '52': { name: 'Gate of Inaction', keyword: 'Stillness', description: 'Stillness and the mountain; the power of non-doing.', shadow: 'Stress', gift: 'Restraint', siddhi: 'Stillness' },
  '53': { name: 'Gate of Beginnings', keyword: 'Starting', description: 'Development and the energy to begin new things.', shadow: 'Immaturity', gift: 'Initiation', siddhi: 'Emergence' },
  '54': { name: 'Gate of Ambition', keyword: 'Ambition', description: 'Ambition and drive to rise up through transformation.', shadow: 'Greed', gift: 'Aspiration', siddhi: 'Ascension' },
  '55': { name: 'Gate of Spirit', keyword: 'Spirit', description: 'Abundance of spirit; emotional richness and melancholy.', shadow: 'Victimization', gift: 'Responsiveness', siddhi: 'Freedom' },
  '56': { name: 'Gate of Stimulation', keyword: 'Storytelling', description: 'Stimulation through stories, beliefs, and experiences.', shadow: 'Distraction', gift: 'Enrichment', siddhi: 'Illumination' },
  '57': { name: 'Gate of Intuitive Clarity', keyword: 'Intuition', description: 'Gentle intuition in the now; clarity through the present.', shadow: 'Unease', gift: 'Intuition', siddhi: 'Clarity' },
  '58': { name: 'Gate of Vitality', keyword: 'Vitality', description: 'Vitality and joy in the perfection of all things.', shadow: 'Dissatisfaction', gift: 'Vitality', siddhi: 'Bliss' },
  '59': { name: 'Gate of Sexuality', keyword: 'Intimacy', description: 'Dispersion and the breaking down of barriers to intimacy.', shadow: 'Dishonesty', gift: 'Intimacy', siddhi: 'Transparency' },
  '60': { name: 'Gate of Acceptance', keyword: 'Limitation', description: 'Acceptance of limitations as the catalyst for transcendence.', shadow: 'Rigidity', gift: 'Realism', siddhi: 'Justice' },
  '61': { name: 'Gate of Mystery', keyword: 'Inner Truth', description: 'Inner truth and the mystery of all knowing.', shadow: 'Psychosis', gift: 'Inspiration', siddhi: 'Sanctity' },
  '62': { name: 'Gate of Detail', keyword: 'Details', description: 'Detail and the logic of naming what is real.', shadow: 'Intellectualization', gift: 'Precision', siddhi: 'Impeccability' },
  '63': { name: 'Gate of Doubt', keyword: 'Doubt', description: 'Logical doubt that ensures only what is proven endures.', shadow: 'Doubt', gift: 'Inquiry', siddhi: 'Truth' },
  '64': { name: 'Gate of Confusion', keyword: 'Confusion', description: 'Before completion; creative confusion that leads to clarity.', shadow: 'Confusion', gift: 'Imagination', siddhi: 'Illumination' },
}

export const MOON_PHASES = [
  { name: 'New Moon', emoji: '🌑', energy: 'New beginnings, setting intentions, planting seeds', journal_prompt: 'What new intentions am I setting this lunar cycle? What am I calling in?' },
  { name: 'Waxing Crescent', emoji: '🌒', energy: 'Building momentum, taking first steps, faith', journal_prompt: 'What small steps am I taking toward my intentions?' },
  { name: 'First Quarter', emoji: '🌓', energy: 'Decision points, challenges, taking action', journal_prompt: 'What obstacles have come up? How am I responding to challenges?' },
  { name: 'Waxing Gibbous', emoji: '🌔', energy: 'Refinement, trust, editing, persistence', journal_prompt: 'What needs refining in my approach? Where am I being called to trust?' },
  { name: 'Full Moon', emoji: '🌕', energy: 'Illumination, completion, release, clarity', journal_prompt: 'What has been illuminated for me? What am I releasing?' },
  { name: 'Waning Gibbous', emoji: '🌖', energy: 'Gratitude, sharing, teaching, reflection', journal_prompt: 'What wisdom have I gathered? How am I sharing it?' },
  { name: 'Last Quarter', emoji: '🌗', energy: 'Letting go, forgiveness, releasing', journal_prompt: 'What am I consciously letting go of? What no longer serves me?' },
  { name: 'Waning Crescent', emoji: '🌘', energy: 'Rest, surrender, integration, completion', journal_prompt: 'How am I honoring my need for rest and integration?' },
]

export const HD_PROFILES = {
  '1/3': { name: 'Investigator/Martyr', theme: 'Trial and Error Foundation', description: 'You need a solid foundation of knowledge (Line 1) and you learn through trial and error (Line 3). Your life is an experiment.' },
  '1/4': { name: 'Investigator/Opportunist', theme: 'Established Foundation', description: 'You build a foundation and share it with your network. Security and relationships are central.' },
  '2/4': { name: 'Hermit/Opportunist', theme: 'The Natural', description: 'You are a natural talent who needs to be called out of hermitage. Your network recognizes you.' },
  '2/5': { name: 'Hermit/Heretic', theme: 'The Savior', description: 'Others project the role of savior or problem-solver onto you. You need alone time to develop your gifts.' },
  '3/5': { name: 'Martyr/Heretic', theme: 'The Anarchist', description: 'You learn through trial and error and your practical wisdom helps others. Bonds are entered and broken.' },
  '3/6': { name: 'Martyr/Role Model', theme: 'The Anarchist/Role Model', description: 'You have a life in three stages: experimentation, stepping back to observe, then becoming a role model.' },
  '4/6': { name: 'Opportunist/Role Model', theme: 'The Opportunist', description: 'Your network is your destiny. After a period of experimentation, you become a role model for others.' },
  '4/1': { name: 'Opportunist/Investigator', theme: 'The Opportunist', description: 'Your foundational knowledge and network are your keys. Security comes from both.' },
  '5/1': { name: 'Heretic/Investigator', theme: 'The Savior', description: 'You are seen as a practical problem-solver with universalizing solutions. Research gives you credibility.' },
  '5/2': { name: 'Heretic/Hermit', theme: 'The Savior', description: 'Others see a savior in you. You need alone time to develop, and are called out to help when needed.' },
  '6/2': { name: 'Role Model/Hermit', theme: 'The Role Model', description: 'Life in three stages: experimenting (1-30), observing from the roof (30-50), then living as a role model.' },
  '6/3': { name: 'Role Model/Martyr', theme: 'The Role Model', description: 'You carry the wisdom of experience (Line 3 trials) and the objectivity of the role model (Line 6).' },
}

export const DECONDITIONING_PROMPTS = [
  'What decision did I make from my mind instead of my authority today?',
  'Where did I initiate instead of waiting (or vice versa)?',
  'What did I take in from an open center and mistake as my own energy?',
  'Did I compare myself to others today? What was the story beneath it?',
  'What would my signature (satisfaction/peace/success/surprise) have guided me toward?',
  'What is my not-self theme trying to show me today?',
  'In what moments did I feel most like myself — most authentic?',
  'Where did I seek outside validation instead of trusting my inner authority?',
  'What relationships or situations are asking me to compromise my design?',
  'What was I conditioned to believe about myself that I now see as untrue?',
]
